
name: workoutplanner
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=2.19.0-294.0.dev <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.2
  build_runner: ^2.3.2
  flutter_speed_dial: ^6.2.0
  path_provider: ^2.0.11
  isar: ^3.0.5
  isar_flutter_libs: ^3.0.5
  flutter_hooks: ^0.18.0
  hooks_riverpod: ^2.1.1
  riverpod_annotation: ^1.0.6
  audioplayers: ^1.1.1
  flutter_slidable: ^2.0.0
  shared_preferences: ^2.0.15
  flutter_native_splash: ^2.2.16
  awesome_notifications: ^0.7.4+1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  isar_generator: ^3.0.5
  riverpod_generator: ^1.0.6
  flutter_launcher_icons: ^0.11.0



flutter:
  
  uses-material-design: true

  assets:
    - assets/
  
flutter_icons:
  android: true
  ios: true
  image_path: "assets/misc/logo.png"

flutter_native_splash:
  color: "#ffffff"
  image: assets/misc/logo.png    
  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
